### ISSUE TITLE
Problems with example sketches

### ISSUE THREAD

**Issue by per1234** [MrLeeh/plc_standardlib#2]
**examples/timer/pt/tp.ino**: The sketch name doesn't match the folder name so it won't be accessible via the **File > Examples > arduino_plclib** menu. That's easy enough to fix by renaming the sketch but the thing is that the code is identical to examples/timer/tp/tp.ino so maybe it's better to just delete examples/timer/pt/tp.ino?

**examples/timer/ton.ino**: The sketch name doesn't match the folder name so it won't be accessible via the **File > Examples > arduino_plclib** menu. There is already a examples/timer/ton/ton.ino that is different from examples/timer/ton.ino.

**Comment by stlehmann** [comment]
Thanks for the report. Fixed it right away.
